apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: todo-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'todo-api'
        static_configs:
          - targets: ['todo-api:8000']
